#DbLayer: FDB
#fdb_version: 6.2.27
firewalld_http: true
genesis_router: true
genesis_user: position

nohardening: true

genesis_products:
  name: position
  server_version: 1.0.0
  web_version: 1.0.0

java_packages:
  - java-11-openjdk-devel

build_rpm : true

nofirewalld: true
