/**
 *
 *   System              : position
 *   Sub-System          : position Configuration
 *   Version             : 1.0
 *   Copyright           : (c) GENESIS
 *   Date                : 2021-09-07
 *
 *   Function : Provide Dictionary configuration for position.
 *
 *   Modification History
 *
 */

fields {
  field(name = "COUNTERPARTY", type = STRING)
  field(name = "COUNTERPARTY_NAME", type = STRING)
  field(name = "ENTERED_BY", type = STRING)
  field(name = "FIELD_3", type = LONG)
  field(name = "INSTRUMENT_SYMBOL", type = STRING)
  field(name = "PRICE", type = DOUBLE)
  field(name = "QUANTITY", type = LONG)
  field(name = "REFERENCE_PX", type = STRING)
  field(name = "REFERENCE_QTY", type = DOUBLE)
  field(name = "SIDE", type = ENUM("BUY", "SELL", default = "BUY"))
  field(name = "SYMBOL", type = LONG)
  field(name = "TRADE_DATE", type = DATE)
  field(name = "TRADE_DATETIME", type = DATETIME)
  field(name = "TRADE_ID", type = STRING)
  field(name = "REMOTE_TRADE_ID", type = STRING)
  field(name = "TRADE_STATUS", type = ENUM("NEW", "ALLOCATED", "CANCELLED", default = "NEW"))

  // Position
  field(name = "POSITION_ID", type = STRING)  // can be an autogenerated sequence, so declare it as such)
  field(name = "QUANTITY", type = LONG) // total number of shares
  field(name = "VALUE", type = DOUBLE) // position qty multiplied by avg trade price
  field(name = "NOTIONAL", type = DOUBLE) // instrument price multiplied by quantity
  field(name = "PNL", type = DOUBLE) // difference between notional and current market price
  field(name = "BUY_QUANTITY", type = LONG)
  field(name = "SELL_QUANTITY", type = LONG)

  // Charts Data
  field(name = "CHARTS_DATA_ID", type = STRING)
  field(name = "INSTRUMENT_SIDE_ALLOCATION", type = LONG)

  // Company
  field(name = "COMPANY_NAME", type = STRING)
  field(name = "COMPANY_LOCATION", type = STRING)
}
