name: GHpages

# Manually triggered
on:
  workflow_dispatch:

jobs:
  build:

    runs-on: appdev-selfhosted

    steps:

      - uses: actions/checkout@v3

      - name: Configure Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Bootstrap
        working-directory: client
        run: npm run bootstrap

      - name: Build
        working-directory: client/web
        run: npm run build:with-host

      - name: GitHub Pages action
          # You may pin to the exact commit or the version.
          # uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          publish_dir: client/web/dist
          github_token: ${{secrets.GITHUB_TOKEN}}
